### ISSUE TITLE
How do we deal with optional values in go

### ISSUE THREAD

**Issue by EECOLOR** [suffuse/go-suffuse#25]
I raised this issue in order to have a focused place for a discussion.

There are actually two ways to represent the absence of a value:
1. Use an `interface` or `pointer` and return `nil`
2. Use an instance of value that represents the empty one

For `CreateConfig` we return an `Either` like this: `(*SfsConfig, *SfsConfigError)` where we promise that if 
`SfsConfigError` is `nil`, `SfsConfig` is not.

For `Config` in `SfsConfig` we however use `NoPath` as instance and `IsEmpty()` as check (this changed in a recent commit). This same pattern is used by `MaybePath`.

That feels inconsistent.

My personal preference is to use a pointer to indicate a possible `nil` value. It saves us from inventing instances that represent 'non-presence' and allows us to be consistent with the `error` pattern which uses `nil` to represent the absence of an error.

Apart from the usage, it reads a bit better in the following cases:

```
type SfsConfig struct {
  VolName string
  Config *Path
  Mountpoint Path
  LogLevel lg.Lvl
  Paths []Path
}
```

```
func MaybePath(path string, err error) *Path {
  if err != nil { return nil }
  return &Path(path)
}
```

In the above examples it's clear we need to check for `nil` for the ones marked with a `*`

I have not investigated what problems we would encounter but I'm eager to hear your opinion.

**Comment by paulp** [comment]
Inconsistency to this point is mostly a result of my not being sure when to use interfaces, structs as values, and structs as pointers in go.

I believe I can simplify that equation now. To a first approximation, here's what you use when:
- interfaces: never
- structs as values: never
- structs as pointers: the rest of the time

I'm fine with nil-as-failure. My ambitions in this domain revolve primarily around limiting the scope of the blizzard of go-inflicted redundancy.

But really, forget interfaces and forget value structs. So much complication fell away when I gave up on any kind of inheritance-esque or ADT-esque abstraction and just made a single Inode class with a bunch of methods which return nil when inapplicable. (This is wip-to-come.) I'd issue a failing grade for it in a better language, here it's just good sense.

**Comment by EECOLOR** [comment]
Could you push the branch so that I can get a better idea of what you mean?

Will it replace `Path`?

**Comment by paulp** [comment]
I can't push it the way it is. I'll show you something soon. Don't make me afraid to even mention work in progress. It's not going to touch Path though. It's the interface with fuse - the implementation of the fs.Node interface.

**Comment by EECOLOR** [comment]
It's no problem. I'm just unclear about you mean with `single Inode class` as there is no such thing as a class in go. I have no intention to make you afraid to mention work in progress, haha.

I'll then massage `Path` to the same structure just to see what I come across and get a better feel of the terrain.

**Comment by paulp** [comment]
If I say "class" in a go context I can only mean struct.

**Comment by EECOLOR** [comment]
You said: 'interfaces: never'. I'm sure you mean almost never unless there are going to be useful implementations where functionality is important. A good example I think is `Rule`.

**Comment by paulp** [comment]
There will be places where interfaces are unavoidable. What I learned is that the time for the interface is when you have no other choice and not before.

**Comment by EECOLOR** [comment]
Good, I think I have a good view
