### ISSUE TITLE
Missing prerequisite in readme

### ISSUE THREAD

**Issue by rintcius** [suffuse/go-suffuse#28]
I got exception below after following the instructions in the readme.
Turned out that this fixed it:

```
brew install Caskroom/cask/osxfuse
```

Not sure if that's the intended fix though.

---

Exception:

```
user@MacBook-Pro:~/workspaces/go/src$ suffuse -m ~/mnt ~/tmp/scratch &
[1] 18717
user@MacBook-Pro:~/workspaces/go/src$ panic: fork/exec /Library/Filesystems/osxfusefs.fs/Support/load_osxfusefs: no such file or directory

goroutine 1 [running]:
github.com/suffuse/go-suffuse/suffuse.MaybePanic(0x513028, 0xc208044990)
    /Users/user/workspaces/go/src/github.com/suffuse/go-suffuse/suffuse/util.go:18 +0x50
main.main()
    /Users/user/workspaces/go/src/github.com/suffuse/go-suffuse/cmd/suffuse/main.go:16 +0xa8

goroutine 5 [syscall]:
os/signal.loop()
    /usr/local/Cellar/go/1.4.2/libexec/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
    /usr/local/Cellar/go/1.4.2/libexec/src/os/signal/signal_unix.go:27 +0x35

[1]+  Exit 2                  suffuse -m ~/mnt ~/tmp/scratch
```

**Comment by paulp** [comment]
`brew install osxfuse` ought to be enough (I'm not sure why it's in both brew and cask.) Thanks for the report.

**Comment by paulp** [comment]
Addressed in #29.

**Comment by rintcius** [comment]
Just FYI (i.e. I'm not suggesting to include it in the readme), `brew install osxfuse` was my first attempt, but I got redirected to `brew install Caskroom/cask/osxfuse` (Yosemite):

```
$ brew install osxfuse
osxfuse: Building this formula from source isn't possible due to OS X
Yosemite and above's strict unsigned kext ban.

You can install with Homebrew Cask:
  brew install Caskroom/cask/osxfuse

You can download from:
  http://sourceforge.net/projects/osxfuse/files/
Error: An unsatisfied requirement failed this build.
```

**Comment by paulp** [comment]
Mmm. Had forgotten about some of this. I guess `brew install Caskroom/cask/osxfuse` works even if you've never installed brew-cask? Because I'd normally write it `brew cask install osxfuse`, but if that presupposes brew-cask then that's one more potential point of failure.

**Comment by rintcius** [comment]
Yeah, I'm not sure about that. I do have `brew-cask` installed so cannot test it easily. I'm happy with  documenting just `brew install osxfuse`. The redirection is a bit clumsy, but I guess it's clear enough for Yosemite users.

It would also be possible to include the officially recommended way of installing https://github.com/osxfuse/osxfuse/wiki/FAQ#21-what-is-the-recommended-way-to-install-fuse-for-os-x - although personally I would then have googled for the `brew` command anyway.

**Comment by paulp** [comment]
The one expands to the other on install, which seems to imply brew having knowledge of brew-cask, which is unfortunate because brew-cask is brain-damagedly written as if brew didn't exist and it was absolutely necessary that it replicate a subset of functionality with different bugs and leave out entirely a larger subset of equally necessary functionality.

```
% brew install Caskroom/cask/osxfuse
==> brew cask install Caskroom/cask/osxfuse
```

Naturally uninstall is asymmetric.

```
% brew uninstall Caskroom/cask/osxfuse
Error: No such keg: /usr/local/Cellar/osxfuse
% brew cask uninstall osxfuse
...
```

I'm going to make all of this an end user problem, as with go.

**Comment by rintcius** [comment]
:+1:
