### ISSUE TITLE
push --force on PRs considered harmful

### ISSUE THREAD

**Issue by paulp** [suffuse/go-suffuse#30]
At this moment the travis badge on our main page claims the build is passing, but it is actually failing. The passing assessment is based on [this successful test run](https://travis-ci.org/suffuse/go-suffuse/builds/70293797) which according to travis was based on commit `9503cea`. That commit doesn't exist in my repository so it was presumably overwritten by a force push.

The commit which was actually merged as #26 is 8cb2b9ff73, which differs in ways unknown from `9503cea` although @EECOLOR should be able to tell us what the difference is since they should both be in his local reflog.

Here is what I think took place:
- Erik pushes `9503cea`.
- Tests pass on travis, pull request 26 is marked green.
- Erik force pushes 8cb2b9ff73 to update pull request 26.
- travis or github loses the event and the tests are never re-run.
- Since PR 26 has already been marked ready-to-merge, it remains so.
- I come along and merge it, breaking the build.

This is an unacceptable sequence of events, most of all because there is absolutely no way for me to reconstruct the delta between `9503cea` and 8cb2b9ff73. The simplest remedy is to disallow force pushes entirely. I'll take other suggestions.

**Comment by paulp** [comment]
Clarification: I mention the travis badge only as a proxy for the fact that the tip of master is genuinely failing the tests. If the state shown by the travis badge is unreliable for other reasons then forget I mentioned it. Our tests are failing right now on a pull request travis marked as having passed the tests, that's the important matter.

**Comment by EECOLOR** [comment]
Oh wow. The sequence of events you describe is likely.

I often force push against a branch with open pull requests. I did not realize travis has a problem with that. Instead of looking into it, I think we should not spend any more time on it and agree we should not do rebases (and with that `push -f`) on open pull requests.

> Since PR 26 has already been marked ready-to-merge, it remains so.

This is not the case on Github as far as I can tell, so that would be a travis problem. I'll test this.

**Comment by EECOLOR** [comment]
I did a test at https://github.com/suffuse/go-suffuse/pull/31 which indeed shows travis not picking up the `push -f`.

The Github 'ready to merge' button does change on a force push. So this is a travis problem.

**Comment by EECOLOR** [comment]
This behavior on travis might be cause by the disabling of `Build pushes`. I turned it back on and will test again.

**Comment by EECOLOR** [comment]
That switch indeed triggers travis to build.

**Comment by EECOLOR** [comment]
The weird thing is that it now builds 2 things on a force push:
- `continuous-integration/travis-ci/push`
- `continuous-integration/travis-ci/pr`

**Comment by EECOLOR** [comment]
I think flipping the switch solved our problem.

**Comment by EECOLOR** [comment]
@paulp Do you agree this can be closed btw? And that we do not need to limit ourselves to regular pushes only?

**Comment by paulp** [comment]
Sure, I'll take your word for it unless it happens again.

**Comment by EECOLOR** [comment]
Agreed

**Comment by JayFoxRox** [comment]
This should be reported to Travis if it wasn't done yet.
If Travis builds on PR it should also build on pushes [forced or not] to PR.
This is different from building on all pushes so this is probably an oversight in Travis [or at least behaviour which should be communicated more clearly].
